- hosts: localhost
  gather_facts: no
  tasks:
   - name: vars for create instances
     include_vars: 
        file: ansible-lab.vars
  
   - name: create instances
     include_role:
        name: deploy-instances

- hosts: all
  gather_facts: true
  remote_user: cloud-user
  become: true
  vars:

    - ansible_ssh_private_key_file: /opt/test_id_rsa
    - ansible_remote_user: cloud-user

  tasks:
   - name: repo
     include_role:
       name: enable-repo

   - name: haproxy
     include_role:
       name: haproxy
     when: inventory_hostname in groups['frontends']
     tags:
       - haproxy

   - name: deploy tomcat
     include_role:
       name: deploy-tomcat
     when: inventory_hostname in groups['apps']

   - name: deploy postgres
     include_role:
        name: deploy-postgres
     when: inventory_hostname in groups['appdbs']
     tags: 
       - postgres
